export function getDevLikeDefaults(nodeEnv) {
  if (nodeEnv !== "test" && nodeEnv !== "development") return null;
  return {
    PORT: "4100",
    CORS_ORIGIN: [
      "http://localhost:5173",
      "http://localhost:3000",
      "http://localhost:3001",
      "http://localhost:3002",
      "http://localhost:3003",
      "http://localhost:3004",
      "http://localhost:3005"
    ].join(","),
    API_PUBLIC_URL: "http://localhost:4100",
    DATABASE_URL: "postgresql://localhost:5432/postgres",
    DATABASE_POOL_MAX_DEV: "12",
    DATABASE_POOL_MAX_TEST: "4",
    DATABASE_POOL_MAX_PROD: "30",
    JWT_ISSUER: "clientside-ecommerce",
    JWT_AUDIENCE: "clientside-ecommerce",
    JWT_EXPIRES_IN: "8h",
    SERVICE_AREA_RADIUS_METERS: "5000",
    DATABASE_SSL_REJECT_UNAUTHORIZED: "false",
    DATABASE_SSL_CA_PEM: "",
    ALLOW_INSECURE_DB_SSL_IN_PRODUCTION: "false",
    GOOGLE_OAUTH_AUTH_URL: "https://accounts.google.com/o/oauth2/v2/auth",
    GOOGLE_OAUTH_TOKEN_URL: "https://oauth2.googleapis.com/token",
    GOOGLE_OAUTH_USERINFO_URL: "https://www.googleapis.com/oauth2/v3/userinfo",
    GOOGLE_OAUTH_SCOPE: "openid email profile",
    OTP_TTL_SECONDS: "300",
    OTP_RESEND_SECONDS: "60",
    OTP_REQUEST_WINDOW_SECONDS: "900",
    OTP_MAX_REQUESTS_PER_WINDOW: "3",
    OTP_MAX_ATTEMPTS: "5",
    LOG_OTP_IN_DEV: "true",
    DISABLE_CUSTOMER_AUTH: "false",
    DEV_AUTH_USER_ID: "00000000-0000-4000-8000-000000000001",
    DEV_AUTH_CUSTOMER_ID: "00000000-0000-4000-8000-000000000001",
    SMTP_HOST: "",
    SMTP_PORT: "587",
    SMTP_USER: "",
    SMTP_PASS: "",
    SMTP_SECURE: "false",
    OTP_FROM_EMAIL: "",
    MSG_AUTH_KEY: "",
    OTP_TEMPLATE_ID: "69f592e0bd83b71e690c8cd2",
    MSG91_SHORT_URL: "0",
    MSG91_REQUEST_TIMEOUT_MS: "15000",
    DISABLE_RATE_LIMITING: "true",
    OBJECT_STORAGE_PUBLIC_BASE_URL: "",
    ENABLE_API_DOCS: "true",
    ALLOW_API_DOCS_IN_PRODUCTION: "false",
    TRUST_PROXY: "false",
    TRUST_PROXY_HOPS: "1",
    JWT_ACCESS_EXPIRES_IN: "15m",
    JWT_REFRESH_EXPIRES_IN: "30d",
    JWT_KEY_ID: "dev-v1",
    JWT_ALLOWED_ALGORITHMS: "HS256",
    STOREFRONT_CATALOG_CACHE_TTL_SEC: "60",
    STOREFRONT_CATALOG_HTTP_CACHE_SEC: "0",
    CATALOG_CACHE_INVALIDATE_TOKEN: "",
    METRICS_SCRAPE_TOKEN: "",
    OUTBOX_BATCH_SIZE: "50",
    OUTBOX_POLL_INTERVAL_MS: "1000",
    OUTBOX_MAX_RETRIES: "5",
    OUTBOX_RETRY_BASE_MS: "250",
    OUTBOX_RETRY_MAX_MS: "30000",
    OUTBOX_HANDLER_TIMEOUT_MS: "10000",
    RETRY_ATTEMPTS: "3",
    RETRY_BASE_DELAY_MS: "120",
    RETRY_MAX_DELAY_MS: "1500",
    SERVER_DB_RETRY_ATTEMPTS: "8",
    SERVER_DB_RETRY_BASE_DELAY_MS: "400",
    SERVER_DB_RETRY_MAX_DELAY_MS: "5000",
    SERVER_START_RETRY_ATTEMPTS: "5",
    SERVER_START_RETRY_BASE_DELAY_MS: "500",
    SERVER_START_RETRY_MAX_DELAY_MS: "6000"
  };
}

